name: Sync Leetcode

on:
  workflow_dispatch:
    inputs:
      commit_msg:
        description: 'Custom commit message header'
        required: false
        default: '[LeetCode Sync]'
        type: string
  schedule:
    - cron: "0 8 * * 6"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          verbose: true
          commit-header: ${{ github.event.inputs.commit_msg || '[LeetCode Sync]' }}
